services:
  - type: web
    name: djibtrade-backend
    env: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn djibtrade.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: djibtrade.settings_prod
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: "True"

databases:
  - name: djibtrade-db
    plan: free
    databaseName: djibtrade
    user: djibtrade_user
