# Generated by Django 5.2.4 on 2025-08-31 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nom du produit', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description du produit', null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix unitaire', max_digits=10)),
                ('currency', models.CharField(choices=[('DJF', 'Franc Djiboutien'), ('USD', 'Dollar Américain')], default='DJF', help_text='Devise du prix', max_length=3)),
                ('stock', models.PositiveIntegerField(default=1, help_text='Quantité disponible')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix total calculé automatiquement', max_digits=12)),
                ('city', models.CharField(blank=True, help_text='Ville de disponibilité', max_length=100, null=True)),
                ('image', models.ImageField(default='products/default_product.jpg', help_text='Image du produit', upload_to='products/')),
                ('contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Téléphone'), ('both', 'WhatsApp et Téléphone')], default='whatsapp', help_text='Méthode de contact préférée', max_length=20)),
                ('whatsapp_contact', models.CharField(blank=True, help_text='Numéro WhatsApp', max_length=20, null=True)),
                ('phone_contact', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text='Lien direct WhatsApp', max_length=255, null=True)),
                ('views', models.PositiveIntegerField(default=0, help_text='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'annonce")),
                ('category', models.ForeignKey(blank=True, help_text='Catégorie du produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('owner', models.ForeignKey(help_text="Utilisateur qui a créé l'annonce.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
