# Generated by Django 5.2.4 on 2025-10-02 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, help_text='Prix total calculé automatiquement', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(help_text='Prix unitaire en Francs Djiboutiens', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
