# Generated by Django 5.2.4 on 2025-10-05 06:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_total_price_alter_product_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='djibtrade/products/default_product.jpg', help_text='Image du produit', max_length=255, verbose_name='image'),
        ),
    ]
