# Generated by Django 5.2.4 on 2025-10-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_total_price_alter_product_unit_price'),
    ]

    operations = [
    ]
