# Generated by Django 5.2.4 on 2025-10-05 12:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20251005_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Image du produit', max_length=255, verbose_name='image'),
        ),
    ]
