# Generated by Django 5.2.4 on 2025-08-15 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Catégorie du produit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, help_text='Ville de disponibilité', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Date de création de l'annonce"),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('DJF', 'Franc Djiboutien'), ('USD', 'Dollar Américain')], default='DJF', help_text='Devise du prix', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Description du produit', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Image du produit', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(help_text="Utilisateur qui a créé l'annonce.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantité disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Nom du produit', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix total calculé automatiquement', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Prix unitaire', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='product',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Lien direct WhatsApp', max_length=255, null=True),
        ),
    ]
